version: '3.8'

services:
  db:
    container_name: todo-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nikita@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

  migrator:
    image: ubuntu:latest
    restart